apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      # hostNetwork: true  # ✅ Moved inside spec
      containers:
      - name: jupyter
        image: lazerhorn/rasa-chat:v1
        ports:
        - containerPort: 8888  # ⚠️ This is unnecessary but allowed


---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    app: jupyter-notebook
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort  # Change to LoadBalancer if running in cloud
